### ISSUE TITLE
Is delay before showing up can be fixed?

### ISSUE THREAD

**Issue by frol** [zzrough/gs-extensions-drop-down-terminal#114]
Does anyone experience a 2-4-second delay after hitting a shortcut before the Drop Down Terminal starts animation at all?

I have a pretty powerful laptop (Core i7, 16GB RAM, SSD drive) though I use integrated video card Intel HD4600. I use Arch Linux, gnome/gtk3 3.16.3, kernel 4.1.6.

**Comment by zzrough** [comment]
The terminal is an external application running gjs (in javascript). This is the only way to start it, and it features a protection as your shell is protected from a shell crash/restart.

It might take some time for the app to start, though on my very-old-gen i5 and SSD it's half a second to start the very first time after a boot. After that, it's always instant.

I do not think this has to do with the graphics card. You always have this lag or just the first time you press the shortcut? (initialization) It would be weird to have always have this lag as the only thing is the window is just moved from outside the screen to its final destination, just like moving an other window. If dragging a window is fast, if the overview is fast, etc... I do not understand why DDT would be slow everytime.

The first time might be different because of the new process created.

**Comment by frol** [comment]
It bothers me not on the first run, but when it is already running for a while. Right now the delay is only 1-2 seconds, which is not that bothersome. I feel like the delay depends on the number of windows (applications) running at the moment, especially, Google Chrome. Thus, I think it might be related to Gnome window manager itself. However, "Activities" shortcut works instantly.

**Comment by pimartin** [comment]
I don't know if it's related but I have noticed a random delay of a few seconds when Kodi is running. There seems to be some weird interaction with that application.

**Comment by RudolfVonKrugstein** [comment]
I have the same delay problem. I am on ubuntu 16.04 running gnome 3.18.4. And unfortantly it is always there when I open the terminal, not just on the first run. It is about 2-3s.

@frol did you anything else this could be related too? I am not running kodi ...

**Comment by frol** [comment]
I do not experience this issue on my system anymore. It seems it was related to some other components which just got updated since then. I'm currently using Gnome-shell 3.20.

**Comment by RudolfVonKrugstein** [comment]
I would like to reopen this, because it is not fixed for me.

I noted: when I open the drop down shell, I see a peak in gnome-shell cpu usage.

Maybe there is something else I can do to debug this?

**Comment by frol** [comment]
@RudolfVonKrugstein Have you tried Gnome-shell 3.20? It seems to me that this issue is not related to the extension itself, but rather to Gnome-shell. Thus, I don't see a point in reopening it here.
