### ISSUE TITLE
Default shortcut key

### ISSUE THREAD

**Issue by hexnut** [zzrough/gs-extensions-drop-down-terminal#218]
What a fantastic extension! So glad I found it.

Curious though, why is the default shortcut key for activation the tilde? This is used quite often inside the shell as an expansion for the user home directory, which conflicts with your default setting. I appreciate the option to provide a custom shortcut. BTW, I chose Ctrl-` as my custom shortcut which seems like a more sensible setting because it does not conflict and is still very convenient.

Just my 2 cents... thanks!

**Comment by zzrough** [comment]
As explained many times already and explained it's not the "tilde", it's the "key above tab", whatever that means on your keyboard, which can be tilde. We can not juggle with all keyboard layout variants. For instance this is a dead key on French keyboards.

I've used this shortcut because it has always been associated to Alt+Key_Above_Tab for a long time to cycle through windows of the current active app, so it's already bound to something in gnome-shell...

I cannot hardcode something else easily. Or this would be for the top 5 keyboard layouts, or no default at all, but I prefer providing a default which works for (I hope) a vast majority of users.
