### ISSUE TITLE
Colours?

### ISSUE THREAD

**Issue by bjesus** [zzrough/gs-extensions-drop-down-terminal#26]
Is there a way to set the colours somewhere? I tried gnome-terminal, I tried .Xresources - the extension seem to ignore all of these.

Is it even possible?

Thanks

**Comment by fherbin** [comment]
gjs bug seems to be closed now : 
https://gitlab.gnome.org/GNOME/gjs/issues/170
https://gitlab.gnome.org/GNOME/gjs/issues/234
:D

**Comment by zzrough** [comment]
thanks to have tackled this on GNOME's gitlab with GJS maintainer !

I was pleased to see your comment but when I followed #170 it does not
seem to be fixed?

I don't remember precisely but I extensively debugged this 3y ago, and i
ended up coding a small C terminal without any problem (well
gnome-terminal works, so there's poor chance it would not work), and I
ported this in Python, and it was not working, just like with GJS, so
I'd say the problem comes from the VTE binding more than GJS, but maybe
I'm wrong and my memory is getting a bit rust.
